# Generated by Django 3.0.2 on 2020-01-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
