# Generated by Django 3.0.2 on 2020-01-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_image_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='image_field',
            new_name='logo',
        ),
    ]
